# 服务端口号
server:
 port: 8001
  servlet:
       #项目路径名称，默认为/
        context-path: /
        session:
         #session失效时间，30m表示30分钟
          timeout: 30m
    #编码
    undertow:
      url-charset: utf-8
spring:
 application:
   name: microservice-order # 对外暴露的服务名

#启动yml配制
spring:
   datasource:
       url: jdbc:mysql://192.168.123.8:3306/ELE_XFTS_System?useSSL=false&useUnicode=true&characterEncoding=utf-8
       username: root
       password: 123456
       initial-size: 50
       min-idle: 20
       max-active: 100
       pool-prepared-statements: true
       max-pool-prepared-statement-per-connection-size: 20
       #SQL查询,用来验证从连接池取出的连接
       validation-query: SELECT 1
       #指明连接是否被空闲连接回收器(如果有)进行检验，如果检测失败，则连接将被从池中去除
       test-while-idle: true
       #在空闲连接回收器线程运行期间休眠的时间值,以毫秒为单位，一般比minEvictableIdleTimeMillis小
       time-between-eviction-runs-millis: 300000
        #在每次空闲连接回收器线程(如果有)运行时检查的连接数量，最好和maxActive一致
       num-tests-per-eviction-run: 50
       #连接池中连接，在时间段内一直空闲，被逐出连接池的时间(1000*60*60)，以毫秒为单位
       min-evictable-idle-time-millis: 3600000
#缓存配制
  redis:
   # Redis服务器地址
    host: ${redis.host}
    # Redis服务器连接端口
    port: ${redis.port}
    # Redis服务器连接密码（默认为空）
    password: ${redis.password}
    lettuce:
          pool:
            #连接池最大连接数（使用负值表示没有限制）
            max-active: -1
            #连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: 1000ms
            #连接池中的最大空闲连接
            max-idle: 100
            #连接池中的最小空闲连接
            min-idle: 50
            #连接超时时间（毫秒）
            shutdown-timeout: 100ms
#mybatis配置
mybatis:
   #mapper包所在地方
   mapper-locations: classpath:mapper/*.xml
   #数字包对象
   type-aliases-package: com.yl.minshuku.dao
   configuration:
      #开启驼峰命名
     map-underscore-to-camel-case: true